apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Chart.Name }}
  namespace: metallb-system
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  addresses:
    - {{ .Values.metallbIP }}
  autoAssign: false
  avoidBuggyIPs: false