apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: nordvpn-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  encryptedData:
    username: AgBK1mbMPU0inny6YTUupNTAkv2XHrgESbMVxmuYo1eu0YcHJ6dL/8q4MDBJKVCWm1x5DJcSHE7TpPBVVkPceNs0k7LhvedH6s3n6EmtGfJDBQPinPHJGz4cpccQ9ObU/7OlQ+AWBjXPBRBUSDPgOMcimnCzUGQ6wxI91LZOFLUfNLRzm3KLFb9jaVgrVnsLpOS8a5lM99yqh+izNNTd83oNXzT9vc7s6PPlggZiRb1RLYP0BoHZKt4YJlonMzpfVDokkqrzqeXRH2OCwIJK7LDwn7O8Z7lTJ6OqFICNw2mEHOU/CWxfv5F4k1XcoXqPdrHvzt/Rp0AIEl/pTB0OoW/iRBvDPcW79Breois5E5d5WvWOPZ0hXgPN+4uAGSinZ5mfBRecoLQ5SK0rN7SLFmvoL33o8TChVb4f0yedbVspUYDuRazKXJ2zkr9cMf3iCrXURDVVI0dOMVV/w299WkmC9cIcBIK8on+zA4/Oi2aypgv3MQJyfY7zNTcI/C0MW4PI70xZREEQKNLqlQQq5/LcTY616wd3GXPFpQimVce5IrZf0g0lnfbMSlQh8bYkurVXZAzuEP6LxmoPomOvy8RY1RHMHq35wiMM7ralrm2asTvSkbSU+xLEBl6Dn5KfchH2AZuvrHqjuY+dJaJtkxxMSLh44vQxngcX9sF+PrhdwSOiLO2izS9BAV5vEB7gEasYPTeHlhtFUiI2SpT/eQDaFRKCa39THZQ=
    password: AgBWuOZN0fvEnRlvkVxZhPcEjO47tuxyC9zvgXHvdXim8MrNlmIi/ZM+5HGRJYuzt7CtkLrKpKuLH9TgqGsNVKHpw58LZOHegbpYF2s/Mji2IVR4cCa/75wTOktvgRPu9HU25RtDLdP+T+rRx4SanXviu1BW1GMpLcN6hRxi4o8qLWfU1JRnPu+7VQZVTXfp2aSo9jSQJrMfGj7zW3o2QckUuWP0lccQNyrsoqGbbIJggdSATUeuMfpPCrBDmjfkd6jeAOZ94CtDZW6fmNZP110qE16zgKGQEWwwj/WFM/r9yfWllNjtB2j8/hwOuByka/8mnhBPvizpXOeZnLxd2vRMXdOYvEIt0XhPQ9PhN9jc0Vbgk04SrBVk2LHCACWH+NL9mgeZpuYw3xGtrponAkFGIU73TqLecYZUzXYQbZvg6KciGTFj61Sl5U44k2oKkJp5zQCVzQxbJ6vCi+2vUku1Di3zmvGBVTn6othvmMIh8So1z0zExBvt7/aeZYdT2H0qFg1/nYx4MhnIUtDbjg0ilhWJTQQU4lbt/K1sCCTDqolPyPsX4/MjDzpqP2T6S7oy6fLABfQdQuDAj9aSM6tg55w6zd1fucpoXIZGPFXuJ/EuXTGXEkG+vV9lyt+KBOCxpp+Hu4OV6KbPzMmL2FnZofIhp4ndXQ9QMhxbjrBBlbU0weFY0JaIPUQZDpwwLxT0X/vfSknaq97ld/VzZhPx4hDBebh5ao8=
  template:
    type: Opaque 
    