apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    metallb.universe.tf/address-pool: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      
spec:
  selector:
    app: {{ .Chart.Name }}

  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
    name: http-proxy
